### PR TITLE
Allow stateClass argument for Entity and default state_class to 'meas…

### PR DESCRIPTION
**Pull request by KidA001**
Fixes https://github.com/neilenns/ambientweather2mqtt/issues/119

### CODE REVIEW

**Comment by neilenns** [comment]
This is failing the automated build process:

> src/entityManager.ts(93,100): error TS2554: Expected 2-5 arguments, but got 6.

**Comment by KidA001** [comment]
> This is failing the automated build process:
> 
> > src/entityManager.ts(93,100): error TS2554: Expected 2-5 arguments, but got 6.

Yup just saw that - didn't realize `Sensor` class was an extension of `Entity` updated and re-pushed the commit

**Comment by neilenns** [comment]
Thanks! Can you provide an example of the updated MQTT details after you've run this with your weather station?

**Comment by KidA001** [comment]
Ok so I'm not sure why I thought I could put this PR without fully testing it. But even though HomeAssistant says the `state_class` should be `None` when the `device_class` is a `timestamp`, it will throw an error if you provide none. Very odd. It prefers that _no_ state_class is set for a timestamp.

I set it to `null` in this case and removed the extra argument to pass `state_class`.

Currently all of your entities are considered `measurements` - however if this changes/grows it seems like device_class and state_class should be coupled together. In that case I'd have a function that you pass a device_class and it returns the proper state_class for that device. For now this seems to work and my HA instance didn't throw any errors regarding `eventDate` anymore!

image

image


Commit has been udpated

**Comment by neilenns** [comment]
HomeAssistant's documentation on this stuff is so bad it drives me crazy.

I'm not wild about explicitly sending the null value for the property in the discovery message. It just shouldn't get sent at all, right? I'd expect the discovery message to have no mention of it at all.

What happens if you set it to `undefined` instead, or don't set it at all?

**Comment by KidA001** [comment]
Yup `undefined` is the way to go, it doesn't end up even showing in MQTT in that case. Sorry I write more Ruby than I do typescript - I see that's also how you handle icon so better to follow that pattern.

image

**Pull request merged**
